[book]
authors = ["Gabor Szabo"]
language = "en"
src = "src"
title = "Git"
# "description": "Git tutorials and training course for people who are serious about Version Control",

# Add github icon to the menu
[output.html]
git-repository-url = "https://github.com/szabgab/git.code-maven.com"
git-repository-icon = "fas-code-fork"
edit-url-template = "https://github.com/szabgab/git.code-maven.com/edit/main/books/git/{path}"

[output.markdown]

# Handle Youtube video embedding and the footer
[preprocessor.embedify]
footer.enable = true
footer.message = "Copyright © 2025 • Created with ❤️  by [Gábor Szabó](https://szabgab.com/)"




